### ISSUE TITLE
Library evaluation tracking issue

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/tempdir#28]
These tasks came from the [libs team evaluation](https://public.etherpad-mozilla.org/p/rust-crate-eval-tempdir) on 2017-03-20.

- [x] [Fix remove_dir_all on windows](https://github.com/rust-lang-nursery/tempdir/issues/15)
- [x] [Update examples to use `?`](https://github.com/rust-lang-nursery/tempdir/issues/23)
- [x] [Add CI for Windows/Mac](https://github.com/rust-lang-nursery/tempdir/issues/24)
- [x] [Add keywords and categories to Cargo.toml](https://github.com/rust-lang-nursery/tempdir/issues/25)
- [x] [Finalize conventions for close](https://github.com/rust-lang-nursery/tempdir/issues/26)
- [x] [Update html_root_url](https://github.com/rust-lang-nursery/tempdir/issues/27)
- [ ] Bump version to 1.0

cc @rust-lang-nursery/libs

**Comment by BurntSushi** [comment]
@brson Thank you for creating this ticket. :-)

**Comment by Susurrus** [comment]
Is this really only needing a version bump and a release?

**Comment by KodrAus** [comment]
@Susurrus sorry this issue is a bit out of date. The current plan is to merge the `tempdir` and `tempfile` crates in #19. The exact shape of that is still a little unclear but the `tempdir` crate as it is here will probably be deprecated. The combined crate will be stable.

Don't worry though, the API in the new combined crate will look pretty much the same as this.

**Comment by KodrAus** [comment]
We've now got the `tempdir` API [merged into `tempfile`](https://github.com/Stebalien/tempfile/pull/33) so I think this is ready to close.

Thank you to everyone who helped polish up `tempdir`!
